services:
  - type: web
    name: signscribe-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/pythonTranslate
      cp -r * /opt/render/project/src/pythonTranslate/
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: https://signscribe-frontend.onrender.com
      - key: MODEL_PATH
        value: TheLastDance.h5
      - key: SEQUENCE_LENGTH
        value: 30
      - key: PREDICTION_THRESHOLD
        value: 0.6
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/pythonTranslate
      sizeGB: 1 