// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcprjjcggrdclqpjxroj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcHJqamNnZ3JkY2xxcGp4cm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTc3MzIsImV4cCI6MjA1ODczMzczMn0.PhIvBxkRMuBfXqGyIhqGu7DQBWXEwePu8YObDawqRfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);